# Generated by Django 3.0.5 on 2020-05-30 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('cp', models.CharField(max_length=5)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiebre', models.BooleanField()),
                ('tos_seca', models.BooleanField()),
                ('asfixia', models.BooleanField()),
                ('perdida_sentidos', models.BooleanField()),
                ('repentino', models.BooleanField()),
                ('resultado', models.BooleanField()),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='AutoTest.Usuario')),
            ],
        ),
    ]
